### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by GitCHQL** [jensstigaard/vmix-js-utils#3]
If there are non-English characters, no output.has question in line 153 at connection-tcp.js

**Comment by jensstigaard** [comment]
Hi @GitCHQL - Just for clearance - Is it because there a non-english character in the output of the XML? (Coming from vMix API). 
Could be a bug in the vMix API not encoding the special characters properly...

What is needed to replicate the issue? Please provide an description of your setup.

Thanks
/ Jens

**Comment by jensstigaard** [comment]
I have identified the bug to be caused by non-ascii characters as GitCHQL also stated - e.g. chineese letters or emojis. This is due to the fact that messages are stated as completed if the number of characters in the buffer equals to the length of the expected bytes in received message sent by vMix. I am currently reimplementing to correctly handle the bytelength, however, it seems like there is still an issue in regard to this.
I have posted on the vMix forums about the issue. https://forums.vmix.com/posts/m70800-TCP-API---XML-data-length-wrong-when-having-non-ascii-characters#post70800
I will update when new info comes on the table.

I will upload the WIP version of the package to let you be able to test it your self.

**Comment by jensstigaard** [comment]
I have commited a new dev branch with the new version. Please not that it is still not working fully.
https://github.com/jensstigaard/vmix-js-utils/blob/dev/src/connection-tcp.js

**Comment by GitCHQL** [comment]
Actually,vmix sometimes just send XML   xx \r\n so i just ignore length of the text

  receivedLines.forEach((item) =>{
                //xml
                if(item.indexOf('<vmix><version>')!==-1){
                    this.emitXmlMessage(item);
                    this.buffered = receivedLines.slice(1)
                }else{
                    this.emitMessage(item);
                }
            })

**Comment by GitCHQL** [comment]
`
  receivedLines.forEach((item) =>{
                //xml
                if(item.indexOf('<vmix><version>')!==-1){
                    this.emitXmlMessage(item);
                    this.buffered = receivedLines.slice(1)
                }else{
                    this.emitMessage(item);
                }
            })`

**Comment by jensstigaard** [comment]
It is not this simple unfortunately, since the XML data can be broken up in several messages, meaning that the it is not sure that the whole XML data is received in one message.

**Comment by GitCHQL** [comment]
I see

**Comment by GitCHQL** [comment]
so it's vmix bug?

**Comment by jensstigaard** [comment]
I think so. I await answer from vMix, to see what can be done. I think you can use the HTTP connection, since it does return the whole response each time over HTTP. But it is not as responsive as TCP.

**Comment by GitCHQL** [comment]
thanks

**Comment by jensstigaard** [comment]
Pull request with bugfix has now been submitted, and version bumped. Please update your NPM dependencies to newest version of vmix-js-utils (v 2.0.2).
